#!/usr/bin/env bash

set -e

# -- Globals -- #

static_dir="static"
content_dir="content"
output_dir="output"

declare -A output_paths

# -- Functions -- #

slugify() {
  local page="${1#$content_dir/}"  # Remove input dir prefix
  page="${page%.*}"                # Remove extension

  if [[ "$page" == "index" ]]; then
    echo "/"
  elif [[ "$page" == */index ]]; then
    echo "/${page%index}"
  else
    echo "/$page/"
  fi
}

# Creates HTML page from Markdown file in output directory
build_page() {
  local page="$1"
  local template="$2"
  local root="$3"

  local slug=$(slugify "$page")

  local output_path="${output_dir}/${page#$content_dir/}"
  output_path="${output_path%.md}.html"
  output_paths["$output_path"]=1

  # Skip if output is newer than source
  if [[ -f "$output_path" && "$output_path" -nt "$page" ]]; then
    return
  else
    echo "[build] $slug"
  fi

  mkdir -p "$(dirname "$output_path")"

  pandoc "$page" \
    --standalone \
    --template "templates/$template.html" \
    --metadata "site:https://ritam.me" \
    --metadata "author:Ritam Sarmah" \
    --metadata "slug:$slug" \
    --metadata-file "${root%/}/metadata.yaml" \
    --output "$output_path"
}

build_site() {
  # Static
  for path in $(fd "" "$static_dir" --type file); do
    output_path="${output_dir}/${path#${static_dir}/}"
    mkdir -p "$(dirname "$output_path")"

    if [ ! -f "$output_path" ] || [ "$path" -nt "$output_path" ]; then
        cp "$path" "$output_path"
        echo "[copy] $path"
    fi

    output_paths["$output_path"]=1
  done

  # Default
  local pages=$(fd . "$content_dir" --maxdepth 1 --extension md)
  for page in $pages; do
    build_page "$page" "default" "$content_dir"
  done

  # Projects
  local projects=$(fd . "$content_dir/projects" --maxdepth 1 --type directory)
  for project in $projects; do
    local pages=$(fd . "$project" --extension md)

    for page in $pages; do
      build_page "$page" "project" "$project"
    done
  done

  # Delete outdated files in output
  fd --no-ignore --type file "" "$output_dir" | while read -r path; do
    if [[ -z "${output_paths[$path]+_}" ]]; then
      echo "[remove] $path"
      rm -f "$path"
    fi
  done
}

# -- Main -- #

mkdir -p "$output_dir"
output_dir=$(realpath "$output_dir")
cd src
build_site
