#!/usr/bin/env bash

# Exit on any command failure and propagate pipe errors
set -e

cleanup() {
  echo "Cleaning up..."
  pkill -P $$
}
trap cleanup EXIT

# Start hot reload in background
fswatch -o content | while read; do
  ./scripts/build
done &

# Delay to finish build
sleep 1

# Start server
serve output
