#!/usr/bin/env bash

# Exit on any command failure and propagate pipe errors
set -e

cleanup() {
  pkill -P $$
}
trap cleanup EXIT

# Run initial build
./scripts/build

# Start hot reload in background
fswatch --one-per-batch src | while read; do
  ./scripts/build
done &

# Delay to finish build
sleep 1

# Start server
serve output
